/* eslint-disable */
var ShellWasm = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(ShellWasm) {
  ShellWasm = ShellWasm || {};


var a;a||(a=typeof ShellWasm !== 'undefined' ? ShellWasm : {});var aa,ba;a.ready=new Promise(function(b,c){aa=b;ba=c});Object.getOwnPropertyDescriptor(a.ready,"_main")||(Object.defineProperty(a.ready,"_main",{configurable:!0,get:function(){e("You are getting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_main",{configurable:!0,set:function(){e("You are setting _main on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_sbrk")||(Object.defineProperty(a.ready,"_sbrk",{configurable:!0,get:function(){e("You are getting _sbrk on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_sbrk",{configurable:!0,set:function(){e("You are setting _sbrk on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackSave")||(Object.defineProperty(a.ready,"_stackSave",{configurable:!0,get:function(){e("You are getting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackSave",{configurable:!0,set:function(){e("You are setting _stackSave on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackRestore")||(Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,get:function(){e("You are getting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackRestore",{configurable:!0,set:function(){e("You are setting _stackRestore on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_stackAlloc")||(Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,get:function(){e("You are getting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_stackAlloc",{configurable:!0,set:function(){e("You are setting _stackAlloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___data_end")||(Object.defineProperty(a.ready,"___data_end",{configurable:!0,get:function(){e("You are getting ___data_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___data_end",{configurable:!0,set:function(){e("You are setting ___data_end on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___wasm_call_ctors")||(Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,get:function(){e("You are getting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___wasm_call_ctors",{configurable:!0,set:function(){e("You are setting ___wasm_call_ctors on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"___errno_location")||(Object.defineProperty(a.ready,"___errno_location",{configurable:!0,get:function(){e("You are getting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"___errno_location",{configurable:!0,set:function(){e("You are setting ___errno_location on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_malloc")||(Object.defineProperty(a.ready,"_malloc",{configurable:!0,get:function(){e("You are getting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_malloc",{configurable:!0,set:function(){e("You are setting _malloc on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_free")||(Object.defineProperty(a.ready,"_free",{configurable:!0,get:function(){e("You are getting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_free",{configurable:!0,set:function(){e("You are setting _free on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_setThrew")||(Object.defineProperty(a.ready,"_setThrew",{configurable:!0,get:function(){e("You are getting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_setThrew",{configurable:!0,set:function(){e("You are setting _setThrew on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"_emscripten_main_thread_process_queued_calls")||(Object.defineProperty(a.ready,"_emscripten_main_thread_process_queued_calls",{configurable:!0,get:function(){e("You are getting _emscripten_main_thread_process_queued_calls on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"_emscripten_main_thread_process_queued_calls",{configurable:!0,
set:function(){e("You are setting _emscripten_main_thread_process_queued_calls on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
Object.getOwnPropertyDescriptor(a.ready,"onRuntimeInitialized")||(Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,get:function(){e("You are getting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}),Object.defineProperty(a.ready,"onRuntimeInitialized",{configurable:!0,set:function(){e("You are setting onRuntimeInitialized on the Promise object, instead of the instance. Use .then() to get called back with the instance, see the MODULARIZE docs in src/settings.js")}}));
var ca={},t;for(t in a)a.hasOwnProperty(t)&&(ca[t]=a[t]);var da="./this.program";if(a.ENVIRONMENT)throw Error("Module.ENVIRONMENT has been deprecated. To force the environment, use the ENVIRONMENT compile-time option (for example, -s ENVIRONMENT=web or -s ENVIRONMENT=node)");var u="";"undefined"!==typeof document&&document.currentScript&&(u=document.currentScript.src);_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="";
if("object"!==typeof window&&"function"!==typeof importScripts)throw Error("not compiled for this environment (did you build to HTML and try to run it not on the web, or set ENVIRONMENT to something - like node - and run it someplace else - like on the web?)");var ea=a.print||console.log.bind(console),w=a.printErr||console.warn.bind(console);for(t in ca)ca.hasOwnProperty(t)&&(a[t]=ca[t]);ca=null;Object.getOwnPropertyDescriptor(a,"arguments")||Object.defineProperty(a,"arguments",{configurable:!0,get:function(){e("Module.arguments has been replaced with plain arguments_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
a.thisProgram&&(da=a.thisProgram);Object.getOwnPropertyDescriptor(a,"thisProgram")||Object.defineProperty(a,"thisProgram",{configurable:!0,get:function(){e("Module.thisProgram has been replaced with plain thisProgram (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"quit")||Object.defineProperty(a,"quit",{configurable:!0,get:function(){e("Module.quit has been replaced with plain quit_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
z("undefined"===typeof a.memoryInitializerPrefixURL,"Module.memoryInitializerPrefixURL option was removed, use Module.locateFile instead");z("undefined"===typeof a.pthreadMainPrefixURL,"Module.pthreadMainPrefixURL option was removed, use Module.locateFile instead");z("undefined"===typeof a.cdInitializerPrefixURL,"Module.cdInitializerPrefixURL option was removed, use Module.locateFile instead");z("undefined"===typeof a.filePackagePrefixURL,"Module.filePackagePrefixURL option was removed, use Module.locateFile instead");
z("undefined"===typeof a.read,"Module.read option was removed (modify read_ in JS)");z("undefined"===typeof a.readAsync,"Module.readAsync option was removed (modify readAsync in JS)");z("undefined"===typeof a.readBinary,"Module.readBinary option was removed (modify readBinary in JS)");z("undefined"===typeof a.setWindowTitle,"Module.setWindowTitle option was removed (modify setWindowTitle in JS)");z("undefined"===typeof a.TOTAL_MEMORY,"Module.TOTAL_MEMORY has been renamed Module.INITIAL_MEMORY");
Object.getOwnPropertyDescriptor(a,"read")||Object.defineProperty(a,"read",{configurable:!0,get:function(){e("Module.read has been replaced with plain read_ (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"readAsync")||Object.defineProperty(a,"readAsync",{configurable:!0,get:function(){e("Module.readAsync has been replaced with plain readAsync (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
Object.getOwnPropertyDescriptor(a,"readBinary")||Object.defineProperty(a,"readBinary",{configurable:!0,get:function(){e("Module.readBinary has been replaced with plain readBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});Object.getOwnPropertyDescriptor(a,"setWindowTitle")||Object.defineProperty(a,"setWindowTitle",{configurable:!0,get:function(){e("Module.setWindowTitle has been replaced with plain setWindowTitle (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});
function fa(b){ha||(ha={});ha[b]||(ha[b]=1,w(b))}var ha,ia;a.wasmBinary&&(ia=a.wasmBinary);Object.getOwnPropertyDescriptor(a,"wasmBinary")||Object.defineProperty(a,"wasmBinary",{configurable:!0,get:function(){e("Module.wasmBinary has been replaced with plain wasmBinary (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});var noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);
Object.getOwnPropertyDescriptor(a,"noExitRuntime")||Object.defineProperty(a,"noExitRuntime",{configurable:!0,get:function(){e("Module.noExitRuntime has been replaced with plain noExitRuntime (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});"object"!==typeof WebAssembly&&e("no native wasm support detected");var A,ja=!1;function z(b,c){b||e("Assertion failed: "+c)}
var ka="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(b,c,d){var f=c+d;for(d=c;b[d]&&!(d>=f);)++d;if(16<d-c&&b.subarray&&ka)return ka.decode(b.subarray(c,d));for(f="";c<d;){var h=b[c++];if(h&128){var g=b[c++]&63;if(192==(h&224))f+=String.fromCharCode((h&31)<<6|g);else{var m=b[c++]&63;224==(h&240)?h=(h&15)<<12|g<<6|m:(240!=(h&248)&&fa("Invalid UTF-8 leading byte 0x"+h.toString(16)+" encountered when deserializing a UTF-8 string on the asm.js/wasm heap to a JS string!"),h=(h&7)<<18|g<<12|m<<6|b[c++]&63);65536>h?f+=String.fromCharCode(h):(h-=
65536,f+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else f+=String.fromCharCode(h)}return f}
function ma(b,c,d,f){if(0<f){f=d+f-1;for(var h=0;h<b.length;++h){var g=b.charCodeAt(h);if(55296<=g&&57343>=g){var m=b.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(d>=f)break;c[d++]=g}else{if(2047>=g){if(d+1>=f)break;c[d++]=192|g>>6}else{if(65535>=g){if(d+2>=f)break;c[d++]=224|g>>12}else{if(d+3>=f)break;2097152<=g&&fa("Invalid Unicode code point 0x"+g.toString(16)+" encountered when serializing a JS string to an UTF-8 string on the asm.js/wasm heap! (Valid unicode code points should be in range 0-0x1FFFFF).");c[d++]=
240|g>>18;c[d++]=128|g>>12&63}c[d++]=128|g>>6&63}c[d++]=128|g&63}}c[d]=0}}function na(b,c,d){z("number"==typeof d,"stringToUTF8(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");ma(b,B,c,d)}function oa(b){for(var c=0,d=0;d<b.length;++d){var f=b.charCodeAt(d);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|b.charCodeAt(++d)&1023);127>=f?++c:c=2047>=f?c+2:65535>=f?c+3:c+4}return c}
var pa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function qa(b,c){z(0==b%2,"Pointer passed to UTF16ToString must be aligned to two bytes!");var d=b>>1;for(var f=d+c/2;!(d>=f)&&sa[d];)++d;d<<=1;if(32<d-b&&pa)return pa.decode(B.subarray(b,d));d=0;for(f="";;){var h=D[b+2*d>>1];if(0==h||d==c/2)return f;++d;f+=String.fromCharCode(h)}}
function ta(b,c,d){z(0==c%2,"Pointer passed to stringToUTF16 must be aligned to two bytes!");z("number"==typeof d,"stringToUTF16(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===d&&(d=2147483647);if(2>d)return 0;d-=2;var f=c;d=d<2*b.length?d/2:b.length;for(var h=0;h<d;++h)D[c>>1]=b.charCodeAt(h),c+=2;D[c>>1]=0;return c-f}function ua(b){return 2*b.length}
function va(b,c){z(0==b%4,"Pointer passed to UTF32ToString must be aligned to four bytes!");for(var d=0,f="";!(d>=c/4);){var h=E[b+4*d>>2];if(0==h)break;++d;65536<=h?(h-=65536,f+=String.fromCharCode(55296|h>>10,56320|h&1023)):f+=String.fromCharCode(h)}return f}
function wa(b,c,d){z(0==c%4,"Pointer passed to stringToUTF32 must be aligned to four bytes!");z("number"==typeof d,"stringToUTF32(str, outPtr, maxBytesToWrite) is missing the third parameter that specifies the length of the output buffer!");void 0===d&&(d=2147483647);if(4>d)return 0;var f=c;d=f+d-4;for(var h=0;h<b.length;++h){var g=b.charCodeAt(h);if(55296<=g&&57343>=g){var m=b.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}E[c>>2]=g;c+=4;if(c+4>d)break}E[c>>2]=0;return c-f}
function xa(b){for(var c=0,d=0;d<b.length;++d){var f=b.charCodeAt(d);55296<=f&&57343>=f&&++d;c+=4}return c}function ya(b,c){z(0<=b.length,"writeArrayToMemory array must have a length (should be an array or typed array)");F.set(b,c)}var G,F,B,D,sa,E,H,za,Aa;
function Ba(b){G=b;a.HEAP8=F=new Int8Array(b);a.HEAP16=D=new Int16Array(b);a.HEAP32=E=new Int32Array(b);a.HEAPU8=B=new Uint8Array(b);a.HEAPU16=sa=new Uint16Array(b);a.HEAPU32=H=new Uint32Array(b);a.HEAPF32=za=new Float32Array(b);a.HEAPF64=Aa=new Float64Array(b)}z(!0,"stack must start aligned");a.TOTAL_STACK&&z(5242880===a.TOTAL_STACK,"the stack size can no longer be determined at runtime");var Ca=a.INITIAL_MEMORY||16777216;
Object.getOwnPropertyDescriptor(a,"INITIAL_MEMORY")||Object.defineProperty(a,"INITIAL_MEMORY",{configurable:!0,get:function(){e("Module.INITIAL_MEMORY has been replaced with plain INITIAL_INITIAL_MEMORY (the initial value can be provided on Module, but after startup the value is only looked for on a local variable of that name)")}});z(5242880<=Ca,"INITIAL_MEMORY should be larger than TOTAL_STACK, was "+Ca+"! (TOTAL_STACK=5242880)");
z("undefined"!==typeof Int32Array&&"undefined"!==typeof Float64Array&&void 0!==Int32Array.prototype.subarray&&void 0!==Int32Array.prototype.set,"JS engine does not provide full typed array support");a.wasmMemory?A=a.wasmMemory:A=new WebAssembly.Memory({initial:Ca/65536,maximum:32768});A&&(G=A.buffer);Ca=G.byteLength;z(0===Ca%65536);z(!0);Ba(G);var J;function Da(){z(!0);H[10953]=34821223;H[10954]=2310721022;E[0]=1668509029}
function Ea(){if(!ja){var b=H[10953],c=H[10954];34821223==b&&2310721022==c||e("Stack overflow! Stack cookie has been overwritten, expected hex dwords 0x89BACDFE and 0x2135467, but received 0x"+c.toString(16)+" "+b.toString(16));1668509029!==E[0]&&e("Runtime error: The application has corrupted its heap memory area (address zero)!")}}var Fa=new Int16Array(1),Ga=new Int8Array(Fa.buffer);Fa[0]=25459;if(115!==Ga[0]||99!==Ga[1])throw"Runtime error: expected the system to be little-endian!";
var Ha=[],Ia=[],Ja=[],Ka=[],La=!1;function Ma(){var b=a.preRun.shift();Ha.unshift(b)}z(Math.imul,"This browser does not support Math.imul(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");z(Math.fround,"This browser does not support Math.fround(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");z(Math.clz32,"This browser does not support Math.clz32(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");
z(Math.trunc,"This browser does not support Math.trunc(), build with LEGACY_VM_SUPPORT or POLYFILL_OLD_MATH_FUNCTIONS to add in a polyfill");var K=0,L=null,Na=null,Oa={};
function Pa(){K++;a.monitorRunDependencies&&a.monitorRunDependencies(K);z(!Oa["wasm-instantiate"]);Oa["wasm-instantiate"]=1;null===L&&"undefined"!==typeof setInterval&&(L=setInterval(function(){if(ja)clearInterval(L),L=null;else{var b=!1,c;for(c in Oa)b||(b=!0,w("still waiting on run dependencies:")),w("dependency: "+c);b&&w("(end of list)")}},1E4))}a.preloadedImages={};a.preloadedAudios={};
function e(b){if(a.onAbort)a.onAbort(b);w(b);ja=!0;b="abort("+b+") at ";a:{var c=Error();if(!c.stack){try{throw Error();}catch(d){c=d}if(!c.stack){c="(no stack trace available)";break a}}c=c.stack.toString()}a.extraStackTrace&&(c+="\n"+a.extraStackTrace());c=Qa(c);b=new WebAssembly.RuntimeError(b+c);ba(b);throw b;}
function Ra(){e("Filesystem support (FS) was not included. The problem is that you are using files from JS, but files were not used from C/C++, so filesystem support was not auto-included. You can force-include filesystem support with  -s FORCE_FILESYSTEM=1")}a.FS_createDataFile=function(){Ra()};a.FS_createPreloadedFile=function(){Ra()};
function Sa(){var b=Ta;return String.prototype.startsWith?b.startsWith("data:application/octet-stream;base64,"):0===b.indexOf("data:application/octet-stream;base64,")}function M(b){return function(){var c=a.asm;z(La,"native function `"+b+"` called before runtime initialization");z(!0,"native function `"+b+"` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)");c[b]||z(c[b],"exported native function `"+b+"` not found");return c[b].apply(null,arguments)}}var Ta="shellWasm.wasm";
if(!Sa()){var Ua=Ta;Ta=a.locateFile?a.locateFile(Ua,u):u+Ua}function Va(){try{if(ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){e(b)}}function Wa(){return ia||"function"!==typeof fetch?Promise.resolve().then(Va):fetch(Ta,{credentials:"same-origin"}).then(function(b){if(!b.ok)throw"failed to load wasm binary file at '"+Ta+"'";return b.arrayBuffer()}).catch(function(){return Va()})}
function Xa(b){for(;0<b.length;){var c=b.shift();if("function"==typeof c)c(a);else{var d=c.U;"number"===typeof d?void 0===c.L?J.get(d)():J.get(d)(c.L):d(void 0===c.L?null:c.L)}}}function Qa(b){return b.replace(/\b_Z[\w\d_]+/g,function(c){fa("warning: build with  -s DEMANGLE_SUPPORT=1  to link in libcxxabi demangling");return c===c?c:c+" ["+c+"]"})}
function Ya(b){this.b=b-16;this.ha=function(c){E[this.b+8>>2]=c};this.ea=function(c){E[this.b+0>>2]=c};this.fa=function(){E[this.b+4>>2]=0};this.da=function(){F[this.b+12>>0]=0};this.ga=function(){F[this.b+13>>0]=0};this.Y=function(c,d){this.ha(c);this.ea(d);this.fa();this.da();this.ga()}}function Za(){return 0<Za.R}function $a(b){switch(b){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+b);}}var ab=void 0;
function N(b){for(var c="";B[b];)c+=ab[B[b++]];return c}var bb={},O={},cb={};function db(b){if(void 0===b)return"_unknown";b=b.replace(/[^a-zA-Z0-9_]/g,"$");var c=b.charCodeAt(0);return 48<=c&&57>=c?"_"+b:b}function eb(b,c){b=db(b);return(new Function("body","return function "+b+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(c)}
function fb(b){var c=Error,d=eb(b,function(f){this.name=b;this.message=f;f=Error(f).stack;void 0!==f&&(this.stack=this.toString()+"\n"+f.replace(/^Error(:[^\n]*)?\n/,""))});d.prototype=Object.create(c.prototype);d.prototype.constructor=d;d.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return d}var gb=void 0;function P(b){throw new gb(b);}var hb=void 0;function ib(b){throw new hb(b);}
function Q(b,c,d){function f(l){l=d(l);l.length!==b.length&&ib("Mismatched type converter count");for(var p=0;p<b.length;++p)R(b[p],l[p])}b.forEach(function(l){cb[l]=c});var h=Array(c.length),g=[],m=0;c.forEach(function(l,p){O.hasOwnProperty(l)?h[p]=O[l]:(g.push(l),bb.hasOwnProperty(l)||(bb[l]=[]),bb[l].push(function(){h[p]=O[l];++m;m===g.length&&f(h)}))});0===g.length&&f(h)}
function R(b,c,d){d=d||{};if(!("argPackAdvance"in c))throw new TypeError("registerType registeredInstance requires argPackAdvance");var f=c.name;b||P('type "'+f+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(b)){if(d.X)return;P("Cannot register type '"+f+"' twice")}O[b]=c;delete cb[b];bb.hasOwnProperty(b)&&(c=bb[b],delete bb[b],c.forEach(function(h){h()}))}function jb(b){return{count:b.count,v:b.v,B:b.B,b:b.b,f:b.f,i:b.i,j:b.j}}
function kb(b){P(b.a.f.c.name+" instance already deleted")}var lb=!1;function mb(){}function nb(b){--b.count.value;0===b.count.value&&(b.i?b.j.u(b.i):b.f.c.u(b.b))}function ob(b){if("undefined"===typeof FinalizationGroup)return ob=function(c){return c},b;lb=new FinalizationGroup(function(c){for(var d=c.next();!d.done;d=c.next())d=d.value,d.b?nb(d):console.warn("object already deleted: "+d.b)});ob=function(c){lb.register(c,c.a,c.a);return c};mb=function(c){lb.unregister(c.a)};return ob(b)}
var pb=void 0,qb=[];function rb(){for(;qb.length;){var b=qb.pop();b.a.v=!1;b["delete"]()}}function T(){}var sb={};function tb(b,c,d){if(void 0===b[c].g){var f=b[c];b[c]=function(){b[c].g.hasOwnProperty(arguments.length)||P("Function '"+d+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+b[c].g+")!");return b[c].g[arguments.length].apply(this,arguments)};b[c].g=[];b[c].g[f.F]=f}}
function ub(b,c,d){a.hasOwnProperty(b)?((void 0===d||void 0!==a[b].g&&void 0!==a[b].g[d])&&P("Cannot register public name '"+b+"' twice"),tb(a,b,b),a.hasOwnProperty(d)&&P("Cannot register multiple overloads of a function with the same number of arguments ("+d+")!"),a[b].g[d]=c):(a[b]=c,void 0!==d&&(a[b].pa=d))}function vb(b,c,d,f,h,g,m,l){this.name=b;this.constructor=c;this.o=d;this.u=f;this.l=h;this.V=g;this.D=m;this.T=l;this.aa=[]}
function wb(b,c,d){for(;c!==d;)c.D||P("Expected null or instance of "+d.name+", got an instance of "+c.name),b=c.D(b),c=c.l;return b}function xb(b,c){if(null===c)return this.M&&P("null is not a valid "+this.name),0;c.a||P('Cannot pass "'+yb(c)+'" as a '+this.name);c.a.b||P("Cannot pass deleted object as a pointer of type "+this.name);return wb(c.a.b,c.a.f.c,this.c)}
function zb(b,c){if(null===c){this.M&&P("null is not a valid "+this.name);if(this.H){var d=this.ba();null!==b&&b.push(this.u,d);return d}return 0}c.a||P('Cannot pass "'+yb(c)+'" as a '+this.name);c.a.b||P("Cannot pass deleted object as a pointer of type "+this.name);!this.G&&c.a.f.G&&P("Cannot convert argument of type "+(c.a.j?c.a.j.name:c.a.f.name)+" to parameter type "+this.name);d=wb(c.a.b,c.a.f.c,this.c);if(this.H)switch(void 0===c.a.i&&P("Passing raw pointer to smart pointer is illegal"),this.ia){case 0:c.a.j===
this?d=c.a.i:P("Cannot convert argument of type "+(c.a.j?c.a.j.name:c.a.f.name)+" to parameter type "+this.name);break;case 1:d=c.a.i;break;case 2:if(c.a.j===this)d=c.a.i;else{var f=c.clone();d=this.ca(d,U(function(){f["delete"]()}));null!==b&&b.push(this.u,d)}break;default:P("Unsupporting sharing policy")}return d}
function Ab(b,c){if(null===c)return this.M&&P("null is not a valid "+this.name),0;c.a||P('Cannot pass "'+yb(c)+'" as a '+this.name);c.a.b||P("Cannot pass deleted object as a pointer of type "+this.name);c.a.f.G&&P("Cannot convert argument of type "+c.a.f.name+" to parameter type "+this.name);return wb(c.a.b,c.a.f.c,this.c)}function Bb(b){return this.fromWireType(H[b>>2])}function Cb(b,c,d){if(c===d)return b;if(void 0===d.l)return null;b=Cb(b,c,d.l);return null===b?null:d.T(b)}var Db={};
function Eb(b,c){for(void 0===c&&P("ptr should not be undefined");b.l;)c=b.D(c),b=b.l;return Db[c]}function Fb(b,c){c.f&&c.b||ib("makeClassHandle requires ptr and ptrType");!!c.j!==!!c.i&&ib("Both smartPtrType and smartPtr must be specified");c.count={value:1};return ob(Object.create(b,{a:{value:c}}))}function V(b,c,d,f){this.name=b;this.c=c;this.M=d;this.G=f;this.H=!1;this.u=this.ca=this.ba=this.P=this.ia=this.$=void 0;void 0!==c.l?this.toWireType=zb:(this.toWireType=f?xb:Ab,this.m=null)}
function Gb(b,c,d){a.hasOwnProperty(b)||ib("Replacing nonexistant public symbol");void 0!==a[b].g&&void 0!==d?a[b].g[d]=c:(a[b]=c,a[b].F=d)}
function Hb(b,c){z(0<=b.indexOf("j"),"getDynCaller should only be called with i64 sigs");var d=[];return function(){d.length=arguments.length;for(var f=0;f<arguments.length;f++)d[f]=arguments[f];-1!=b.indexOf("j")?(z("dynCall_"+b in a,"bad function pointer type - no table for sig '"+b+"'"),d&&d.length?z(d.length===b.substring(1).replace(/j/g,"--").length):z(1==b.length),f=d&&d.length?a["dynCall_"+b].apply(null,[c].concat(d)):a["dynCall_"+b].call(null,c)):(z(J.get(c),"missing table entry in dynCall: "+
c),f=J.get(c).apply(null,d));return f}}function W(b,c){b=N(b);var d=-1!=b.indexOf("j")?Hb(b,c):J.get(c);"function"!==typeof d&&P("unknown function pointer with signature "+b+": "+c);return d}var Ib=void 0;function Jb(b){b=Kb(b);var c=N(b);X(b);return c}function Lb(b,c){function d(g){h[g]||O[g]||(cb[g]?cb[g].forEach(d):(f.push(g),h[g]=!0))}var f=[],h={};c.forEach(d);throw new Ib(b+": "+f.map(Jb).join([", "]));}function Mb(b,c){for(var d=[],f=0;f<b;f++)d.push(E[(c>>2)+f]);return d}
function Nb(b){for(;b.length;){var c=b.pop();b.pop()(c)}}function Pb(b){var c=Function;if(!(c instanceof Function))throw new TypeError("new_ called with constructor type "+typeof c+" which is not a function");var d=eb(c.name||"unknownFunctionName",function(){});d.prototype=c.prototype;d=new d;b=c.apply(d,b);return b instanceof Object?b:d}
function Qb(b,c,d,f,h){var g=c.length;2>g&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var m=null!==c[1]&&null!==d,l=!1;for(d=1;d<c.length;++d)if(null!==c[d]&&void 0===c[d].m){l=!0;break}var p="void"!==c[0].name,q="",n="";for(d=0;d<g-2;++d)q+=(0!==d?", ":"")+"arg"+d,n+=(0!==d?", ":"")+"arg"+d+"Wired";b="return function "+db(b)+"("+q+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+b+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";l&&(b+="var destructors = [];\n");var v=l?"destructors":"null";q="throwBindingError invoker fn runDestructors retType classParam".split(" ");f=[P,f,h,Nb,c[0],c[1]];m&&(b+="var thisWired = classParam.toWireType("+v+", this);\n");for(d=0;d<g-2;++d)b+="var arg"+d+"Wired = argType"+d+".toWireType("+v+", arg"+d+"); // "+c[d+2].name+"\n",q.push("argType"+d),f.push(c[d+2]);m&&(n="thisWired"+(0<n.length?", ":"")+n);b+=(p?"var rv = ":"")+"invoker(fn"+(0<n.length?", ":"")+n+");\n";if(l)b+=
"runDestructors(destructors);\n";else for(d=m?1:2;d<c.length;++d)g=1===d?"thisWired":"arg"+(d-2)+"Wired",null!==c[d].m&&(b+=g+"_dtor("+g+"); // "+c[d].name+"\n",q.push(g+"_dtor"),f.push(c[d].m));p&&(b+="var ret = retType.fromWireType(rv);\nreturn ret;\n");q.push(b+"}\n");return Pb(q).apply(null,f)}
function Rb(b,c,d){b instanceof Object||P(d+' with invalid "this": '+b);b instanceof c.c.constructor||P(d+' incompatible with "this" of type '+b.constructor.name);b.a.b||P("cannot call emscripten binding method "+d+" on deleted object");return wb(b.a.b,b.a.f.c,c.c)}var Sb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Tb(b){4<b&&0===--Y[b].N&&(Y[b]=void 0,Sb.push(b))}
function U(b){switch(b){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var c=Sb.length?Sb.pop():Y.length;Y[c]={N:1,value:b};return c}}function Ub(b,c,d){switch(c){case 0:return function(f){return this.fromWireType((d?F:B)[f])};case 1:return function(f){return this.fromWireType((d?D:sa)[f>>1])};case 2:return function(f){return this.fromWireType((d?E:H)[f>>2])};default:throw new TypeError("Unknown integer type: "+b);}}
function Vb(b,c){var d=O[b];void 0===d&&P(c+" has unknown type "+Jb(b));return d}function yb(b){if(null===b)return"null";var c=typeof b;return"object"===c||"array"===c||"function"===c?b.toString():""+b}function Wb(b,c){switch(c){case 2:return function(d){return this.fromWireType(za[d>>2])};case 3:return function(d){return this.fromWireType(Aa[d>>3])};default:throw new TypeError("Unknown float type: "+b);}}
function Xb(b,c,d){switch(c){case 0:return d?function(f){return F[f]}:function(f){return B[f]};case 1:return d?function(f){return D[f>>1]}:function(f){return sa[f>>1]};case 2:return d?function(f){return E[f>>2]}:function(f){return H[f>>2]};default:throw new TypeError("Unknown integer type: "+b);}}function Z(b){b||P("Cannot use deleted val. handle = "+b);return Y[b].value}var Yb={};function Zb(b){var c=Yb[b];return void 0===c?N(b):c}var $b=[];
function ac(){return"object"===typeof globalThis?globalThis:Function("return this")()}function bc(b){var c=$b.length;$b.push(b);return c}function cc(b,c){for(var d=Array(b),f=0;f<b;++f)d[f]=Vb(E[(c>>2)+f],"parameter "+f);return d}var dc={};
function ec(){if(!fc){var b={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},c;for(c in dc)b[c]=dc[c];var d=[];for(c in b)d.push(c+"="+b[c]);fc=d}return fc}var fc,gc=[null,[],[]],hc={};function ic(b){return 0===b%4&&(0!==b%100||0===b%400)}function jc(b,c){for(var d=0,f=0;f<=c;d+=b[f++]);return d}
var kc=[31,29,31,30,31,30,31,31,30,31,30,31],lc=[31,28,31,30,31,30,31,31,30,31,30,31];function mc(b,c){for(b=new Date(b.getTime());0<c;){var d=b.getMonth(),f=(ic(b.getFullYear())?kc:lc)[d];if(c>f-b.getDate())c-=f-b.getDate()+1,b.setDate(1),11>d?b.setMonth(d+1):(b.setMonth(0),b.setFullYear(b.getFullYear()+1));else{b.setDate(b.getDate()+c);break}}return b}
function nc(b,c,d,f){function h(k,r,y){for(k="number"===typeof k?k.toString():k||"";k.length<r;)k=y[0]+k;return k}function g(k,r){return h(k,r,"0")}function m(k,r){function y(I){return 0>I?-1:0<I?1:0}var C;0===(C=y(k.getFullYear()-r.getFullYear()))&&0===(C=y(k.getMonth()-r.getMonth()))&&(C=y(k.getDate()-r.getDate()));return C}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function p(k){k=mc(new Date(k.h+1900,0,1),k.K);var r=new Date(k.getFullYear()+1,0,4),y=l(new Date(k.getFullYear(),0,4));r=l(r);return 0>=m(y,k)?0>=m(r,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var q=E[f+40>>2];f={la:E[f>>2],ka:E[f+4>>2],I:E[f+8>>2],C:E[f+12>>2],A:E[f+16>>2],h:E[f+20>>2],J:E[f+24>>2],K:E[f+28>>2],qa:E[f+32>>2],ja:E[f+36>>2],
ma:q?q?la(B,q,void 0):"":""};d=d?la(B,d,void 0):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var n in q)d=d.replace(new RegExp(n,"g"),q[n]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");q={"%a":function(k){return v[k.J].substring(0,3)},"%A":function(k){return v[k.J]},"%b":function(k){return x[k.A].substring(0,3)},"%B":function(k){return x[k.A]},"%C":function(k){return g((k.h+1900)/100|0,2)},"%d":function(k){return g(k.C,2)},"%e":function(k){return h(k.C,2," ")},"%g":function(k){return p(k).toString().substring(2)},"%G":function(k){return p(k)},"%H":function(k){return g(k.I,2)},"%I":function(k){k=
k.I;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.C+jc(ic(k.h+1900)?kc:lc,k.A-1),3)},"%m":function(k){return g(k.A+1,2)},"%M":function(k){return g(k.ka,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.I&&12>k.I?"AM":"PM"},"%S":function(k){return g(k.la,2)},"%t":function(){return"\t"},"%u":function(k){return k.J||7},"%U":function(k){var r=new Date(k.h+1900,0,1),y=0===r.getDay()?r:mc(r,7-r.getDay());k=new Date(k.h+1900,k.A,k.C);return 0>m(y,k)?g(Math.ceil((31-y.getDate()+
(jc(ic(k.getFullYear())?kc:lc,k.getMonth()-1)-31)+k.getDate())/7),2):0===m(y,r)?"01":"00"},"%V":function(k){var r=new Date(k.h+1901,0,4),y=l(new Date(k.h+1900,0,4));r=l(r);var C=mc(new Date(k.h+1900,0,1),k.K);return 0>m(C,y)?"53":0>=m(r,C)?"01":g(Math.ceil((y.getFullYear()<k.h+1900?k.K+32-y.getDate():k.K+1-y.getDate())/7),2)},"%w":function(k){return k.J},"%W":function(k){var r=new Date(k.h,0,1),y=1===r.getDay()?r:mc(r,0===r.getDay()?1:7-r.getDay()+1);k=new Date(k.h+1900,k.A,k.C);return 0>m(y,k)?g(Math.ceil((31-
y.getDate()+(jc(ic(k.getFullYear())?kc:lc,k.getMonth()-1)-31)+k.getDate())/7),2):0===m(y,r)?"01":"00"},"%y":function(k){return(k.h+1900).toString().substring(2)},"%Y":function(k){return k.h+1900},"%z":function(k){k=k.ja;var r=0<=k;k=Math.abs(k)/60;return(r?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.ma},"%%":function(){return"%"}};for(n in q)0<=d.indexOf(n)&&(d=d.replace(new RegExp(n,"g"),q[n](f)));n=oc(d);if(n.length>c)return 0;ya(n,b);return n.length-1}
for(var pc=Array(256),qc=0;256>qc;++qc)pc[qc]=String.fromCharCode(qc);ab=pc;gb=a.BindingError=fb("BindingError");hb=a.InternalError=fb("InternalError");T.prototype.isAliasOf=function(b){if(!(this instanceof T&&b instanceof T))return!1;var c=this.a.f.c,d=this.a.b,f=b.a.f.c;for(b=b.a.b;c.l;)d=c.D(d),c=c.l;for(;f.l;)b=f.D(b),f=f.l;return c===f&&d===b};
T.prototype.clone=function(){this.a.b||kb(this);if(this.a.B)return this.a.count.value+=1,this;var b=ob(Object.create(Object.getPrototypeOf(this),{a:{value:jb(this.a)}}));b.a.count.value+=1;b.a.v=!1;return b};T.prototype["delete"]=function(){this.a.b||kb(this);this.a.v&&!this.a.B&&P("Object already scheduled for deletion");mb(this);nb(this.a);this.a.B||(this.a.i=void 0,this.a.b=void 0)};T.prototype.isDeleted=function(){return!this.a.b};
T.prototype.deleteLater=function(){this.a.b||kb(this);this.a.v&&!this.a.B&&P("Object already scheduled for deletion");qb.push(this);1===qb.length&&pb&&pb(rb);this.a.v=!0;return this};V.prototype.W=function(b){this.P&&(b=this.P(b));return b};V.prototype.O=function(b){this.u&&this.u(b)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=Bb;V.prototype.deleteObject=function(b){if(null!==b)b["delete"]()};
V.prototype.fromWireType=function(b){function c(){return this.H?Fb(this.c.o,{f:this.$,b:d,j:this,i:b}):Fb(this.c.o,{f:this,b})}var d=this.W(b);if(!d)return this.O(b),null;var f=Eb(this.c,d);if(void 0!==f){if(0===f.a.count.value)return f.a.b=d,f.a.i=b,f.clone();f=f.clone();this.O(b);return f}f=this.c.V(d);f=sb[f];if(!f)return c.call(this);f=this.G?f.S:f.pointerType;var h=Cb(d,this.c,f.c);return null===h?c.call(this):this.H?Fb(f.c.o,{f,b:h,j:this,i:b}):Fb(f.c.o,{f,b:h})};
a.getInheritedInstanceCount=function(){return Object.keys(Db).length};a.getLiveInheritedInstances=function(){var b=[],c;for(c in Db)Db.hasOwnProperty(c)&&b.push(Db[c]);return b};a.flushPendingDeletes=rb;a.setDelayFunction=function(b){pb=b;qb.length&&pb&&pb(rb)};Ib=a.UnboundTypeError=fb("UnboundTypeError");a.count_emval_handles=function(){for(var b=0,c=5;c<Y.length;++c)void 0!==Y[c]&&++b;return b};a.get_first_emval=function(){for(var b=5;b<Y.length;++b)if(void 0!==Y[b])return Y[b];return null};
function oc(b){var c=Array(oa(b)+1);ma(b,c,0,c.length);return c}Ia.push({U:function(){rc()}});
var uc={__cxa_allocate_exception:function(b){return sc(b+16)+16},__cxa_atexit:function(){},__cxa_throw:function(b,c,d){(new Ya(b)).Y(c,d);"uncaught_exception"in Za?Za.R++:Za.R=1;throw b+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},_embind_register_bool:function(b,c,d,f,h){var g=$a(d);c=N(c);R(b,{name:c,fromWireType:function(m){return!!m},toWireType:function(m,l){return l?f:h},argPackAdvance:8,
readValueFromPointer:function(m){if(1===d)var l=F;else if(2===d)l=D;else if(4===d)l=E;else throw new TypeError("Unknown boolean type size: "+c);return this.fromWireType(l[m>>g])},m:null})},_embind_register_class:function(b,c,d,f,h,g,m,l,p,q,n,v,x){n=N(n);g=W(h,g);l&&(l=W(m,l));q&&(q=W(p,q));x=W(v,x);var k=db(n);ub(k,function(){Lb("Cannot construct "+n+" due to unbound types",[f])});Q([b,c,d],f?[f]:[],function(r){r=r[0];if(f){var y=r.c;var C=y.o}else C=T.prototype;r=eb(k,function(){if(Object.getPrototypeOf(this)!==
I)throw new gb("Use 'new' to construct "+n);if(void 0===S.s)throw new gb(n+" has no accessible constructor");var Ob=S.s[arguments.length];if(void 0===Ob)throw new gb("Tried to invoke ctor of "+n+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(S.s).toString()+") parameters instead!");return Ob.apply(this,arguments)});var I=Object.create(C,{constructor:{value:r}});r.prototype=I;var S=new vb(n,r,I,x,y,g,l,q);y=new V(n,S,!0,!1);C=new V(n+"*",S,!1,!1);var ra=new V(n+
" const*",S,!1,!0);sb[b]={pointerType:C,S:ra};Gb(k,r);return[y,C,ra]})},_embind_register_class_constructor:function(b,c,d,f,h,g){z(0<c);var m=Mb(c,d);h=W(f,h);var l=[g],p=[];Q([],[b],function(q){q=q[0];var n="constructor "+q.name;void 0===q.c.s&&(q.c.s=[]);if(void 0!==q.c.s[c-1])throw new gb("Cannot register multiple constructors with identical number of parameters ("+(c-1)+") for class '"+q.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");
q.c.s[c-1]=function(){Lb("Cannot construct "+q.name+" due to unbound types",m)};Q([],m,function(v){q.c.s[c-1]=function(){arguments.length!==c-1&&P(n+" called with "+arguments.length+" arguments, expected "+(c-1));p.length=0;l.length=c;for(var x=1;x<c;++x)l[x]=v[x].toWireType(p,arguments[x-1]);x=h.apply(null,l);Nb(p);return v[0].fromWireType(x)};return[]});return[]})},_embind_register_class_function:function(b,c,d,f,h,g,m,l){var p=Mb(d,f);c=N(c);g=W(h,g);Q([],[b],function(q){function n(){Lb("Cannot call "+
v+" due to unbound types",p)}q=q[0];var v=q.name+"."+c;l&&q.c.aa.push(c);var x=q.c.o,k=x[c];void 0===k||void 0===k.g&&k.className!==q.name&&k.F===d-2?(n.F=d-2,n.className=q.name,x[c]=n):(tb(x,c,v),x[c].g[d-2]=n);Q([],p,function(r){r=Qb(v,r,q,g,m);void 0===x[c].g?(r.F=d-2,x[c]=r):x[c].g[d-2]=r;return[]});return[]})},_embind_register_class_property:function(b,c,d,f,h,g,m,l,p,q){c=N(c);h=W(f,h);Q([],[b],function(n){n=n[0];var v=n.name+"."+c,x={get:function(){Lb("Cannot access "+v+" due to unbound types",
[d,m])},enumerable:!0,configurable:!0};p?x.set=function(){Lb("Cannot access "+v+" due to unbound types",[d,m])}:x.set=function(){P(v+" is a read-only property")};Object.defineProperty(n.c.o,c,x);Q([],p?[d,m]:[d],function(k){var r=k[0],y={get:function(){var I=Rb(this,n,v+" getter");return r.fromWireType(h(g,I))},enumerable:!0};if(p){p=W(l,p);var C=k[1];y.set=function(I){var S=Rb(this,n,v+" setter"),ra=[];p(q,S,C.toWireType(ra,I));Nb(ra)}}Object.defineProperty(n.c.o,c,y);return[]});return[]})},_embind_register_emval:function(b,
c){c=N(c);R(b,{name:c,fromWireType:function(d){var f=Y[d].value;Tb(d);return f},toWireType:function(d,f){return U(f)},argPackAdvance:8,readValueFromPointer:Bb,m:null})},_embind_register_enum:function(b,c,d,f){function h(){}d=$a(d);c=N(c);h.values={};R(b,{name:c,constructor:h,fromWireType:function(g){return this.constructor.values[g]},toWireType:function(g,m){return m.value},argPackAdvance:8,readValueFromPointer:Ub(c,d,f),m:null});ub(c,h)},_embind_register_enum_value:function(b,c,d){var f=Vb(b,"enum");
c=N(c);b=f.constructor;f=Object.create(f.constructor.prototype,{value:{value:d},constructor:{value:eb(f.name+"_"+c,function(){})}});b.values[d]=f;b[c]=f},_embind_register_float:function(b,c,d){d=$a(d);c=N(c);R(b,{name:c,fromWireType:function(f){return f},toWireType:function(f,h){if("number"!==typeof h&&"boolean"!==typeof h)throw new TypeError('Cannot convert "'+yb(h)+'" to '+this.name);return h},argPackAdvance:8,readValueFromPointer:Wb(c,d),m:null})},_embind_register_function:function(b,c,d,f,h,g){var m=
Mb(c,d);b=N(b);h=W(f,h);ub(b,function(){Lb("Cannot call "+b+" due to unbound types",m)},c-1);Q([],m,function(l){Gb(b,Qb(b,[l[0],null].concat(l.slice(1)),null,h,g),c-1);return[]})},_embind_register_integer:function(b,c,d,f,h){function g(q){return q}c=N(c);-1===h&&(h=4294967295);var m=$a(d);if(0===f){var l=32-8*d;g=function(q){return q<<l>>>l}}var p=-1!=c.indexOf("unsigned");R(b,{name:c,fromWireType:g,toWireType:function(q,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+
yb(n)+'" to '+this.name);if(n<f||n>h)throw new TypeError('Passing a number "'+yb(n)+'" from JS side to C/C++ side to an argument of type "'+c+'", which is outside the valid range ['+f+", "+h+"]!");return p?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:Xb(c,m,0!==f),m:null})},_embind_register_memory_view:function(b,c,d){function f(g){g>>=2;var m=H;return new h(G,m[g+1],m[g])}var h=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][c];d=N(d);R(b,{name:d,
fromWireType:f,argPackAdvance:8,readValueFromPointer:f},{X:!0})},_embind_register_std_string:function(b,c){c=N(c);var d="std::string"===c;R(b,{name:c,fromWireType:function(f){var h=H[f>>2];if(d)for(var g=f+4,m=0;m<=h;++m){var l=f+4+m;if(m==h||0==B[l]){g=g?la(B,g,l-g):"";if(void 0===p)var p=g;else p+=String.fromCharCode(0),p+=g;g=l+1}}else{p=Array(h);for(m=0;m<h;++m)p[m]=String.fromCharCode(B[f+4+m]);p=p.join("")}X(f);return p},toWireType:function(f,h){h instanceof ArrayBuffer&&(h=new Uint8Array(h));
var g="string"===typeof h;g||h instanceof Uint8Array||h instanceof Uint8ClampedArray||h instanceof Int8Array||P("Cannot pass non-string to std::string");var m=(d&&g?function(){return oa(h)}:function(){return h.length})(),l=sc(4+m+1);H[l>>2]=m;if(d&&g)na(h,l+4,m+1);else if(g)for(g=0;g<m;++g){var p=h.charCodeAt(g);255<p&&(X(l),P("String has UTF-16 code units that do not fit in 8 bits"));B[l+4+g]=p}else for(g=0;g<m;++g)B[l+4+g]=h[g];null!==f&&f.push(X,l);return l},argPackAdvance:8,readValueFromPointer:Bb,
m:function(f){X(f)}})},_embind_register_std_wstring:function(b,c,d){d=N(d);if(2===c){var f=qa;var h=ta;var g=ua;var m=function(){return sa};var l=1}else 4===c&&(f=va,h=wa,g=xa,m=function(){return H},l=2);R(b,{name:d,fromWireType:function(p){for(var q=H[p>>2],n=m(),v,x=p+4,k=0;k<=q;++k){var r=p+4+k*c;if(k==q||0==n[r>>l])x=f(x,r-x),void 0===v?v=x:(v+=String.fromCharCode(0),v+=x),x=r+c}X(p);return v},toWireType:function(p,q){"string"!==typeof q&&P("Cannot pass non-string to C++ string type "+d);var n=
g(q),v=sc(4+n+c);H[v>>2]=n>>l;h(q,v+4,n+c);null!==p&&p.push(X,v);return v},argPackAdvance:8,readValueFromPointer:Bb,m:function(p){X(p)}})},_embind_register_void:function(b,c){c=N(c);R(b,{Z:!0,name:c,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},_emval_as:function(b,c,d){b=Z(b);c=Vb(c,"emval::as");var f=[],h=U(f);E[d>>2]=h;return c.toWireType(f,b)},_emval_call_method:function(b,c,d,f,h){b=$b[b];c=Z(c);d=Zb(d);var g=[];E[f>>2]=U(g);return b(c,d,g,h)},_emval_call_void_method:function(b,
c,d,f){b=$b[b];c=Z(c);d=Zb(d);b(c,d,null,f)},_emval_decref:Tb,_emval_get_global:function(b){if(0===b)return U(ac());b=Zb(b);return U(ac()[b])},_emval_get_method_caller:function(b,c){c=cc(b,c);for(var d=c[0],f=d.name+"_$"+c.slice(1).map(function(q){return q.name}).join("_")+"$",h=["retType"],g=[d],m="",l=0;l<b-1;++l)m+=(0!==l?", ":"")+"arg"+l,h.push("argType"+l),g.push(c[1+l]);f="return function "+db("methodCaller_"+f)+"(handle, name, destructors, args) {\n";var p=0;for(l=0;l<b-1;++l)f+="    var arg"+
l+" = argType"+l+".readValueFromPointer(args"+(p?"+"+p:"")+");\n",p+=c[l+1].argPackAdvance;f+="    var rv = handle[name]("+m+");\n";for(l=0;l<b-1;++l)c[l+1].deleteObject&&(f+="    argType"+l+".deleteObject(arg"+l+");\n");d.Z||(f+="    return retType.toWireType(destructors, rv);\n");h.push(f+"};\n");b=Pb(h).apply(null,g);return bc(b)},_emval_get_property:function(b,c){b=Z(b);c=Z(c);return U(b[c])},_emval_incref:function(b){4<b&&(Y[b].N+=1)},_emval_new_array:function(){return U([])},_emval_new_cstring:function(b){return U(Zb(b))},
_emval_new_object:function(){return U({})},_emval_run_destructors:function(b){Nb(Y[b].value);Tb(b)},_emval_set_property:function(b,c,d){b=Z(b);c=Z(c);d=Z(d);b[c]=d},_emval_take_value:function(b,c){b=Vb(b,"_emval_take_value");b=b.readValueFromPointer(c);return U(b)},abort:function(){e()},emscripten_memcpy_big:function(b,c,d){B.copyWithin(b,c,c+d)},emscripten_resize_heap:function(b){b>>>=0;var c=B.length;z(b>c);if(2147483648<b)return w("Cannot enlarge memory, asked to go up to "+b+" bytes, but the limit is 2147483648 bytes!"),
!1;for(var d=1;4>=d;d*=2){var f=c*(1+.2/d);f=Math.min(f,b+100663296);f=Math.max(16777216,b,f);0<f%65536&&(f+=65536-f%65536);f=Math.min(2147483648,f);a:{var h=f;try{A.grow(h-G.byteLength+65535>>>16);Ba(A.buffer);var g=1;break a}catch(m){console.error("emscripten_realloc_buffer: Attempted to grow heap from "+G.byteLength+" bytes to "+h+" bytes, but got error: "+m)}g=void 0}if(g)return!0}w("Failed to grow the heap from "+c+" bytes to "+f+" bytes, not enough memory!");return!1},environ_get:function(b,
c){var d=0;ec().forEach(function(f,h){var g=c+d;h=E[b+4*h>>2]=g;for(g=0;g<f.length;++g)z(f.charCodeAt(g)===f.charCodeAt(g)&255),F[h++>>0]=f.charCodeAt(g);F[h>>0]=0;d+=f.length+1});return 0},environ_sizes_get:function(b,c){var d=ec();E[b>>2]=d.length;var f=0;d.forEach(function(h){f+=h.length+1});E[c>>2]=f;return 0},fd_close:function(){e("it should not be possible to operate on streams when !SYSCALLS_REQUIRE_FILESYSTEM");return 0},fd_read:function(b,c,d,f){b=hc.oa(b);c=hc.na(b,c,d);E[f>>2]=c;return 0},
fd_seek:function(){e("it should not be possible to operate on streams when !SYSCALLS_REQUIRE_FILESYSTEM")},fd_write:function(b,c,d,f){for(var h=0,g=0;g<d;g++){for(var m=E[c+8*g>>2],l=E[c+(8*g+4)>>2],p=0;p<l;p++){var q=b,n=B[m+p],v=gc[q];z(v);0===n||10===n?((1===q?ea:w)(la(v,0)),v.length=0):v.push(n)}h+=l}E[f>>2]=h;return 0},memory:A,pthread_create:function(){return 6},pthread_join:function(){},setTempRet0:function(){},strftime_l:function(b,c,d,f){return nc(b,c,d,f)},sysconf:function(b){switch(b){case 30:return 16384;
case 85:return 131072;case 132:case 133:case 12:case 137:case 138:case 15:case 235:case 16:case 17:case 18:case 19:case 20:case 149:case 13:case 10:case 236:case 153:case 9:case 21:case 22:case 159:case 154:case 14:case 77:case 78:case 139:case 80:case 81:case 82:case 68:case 67:case 164:case 11:case 29:case 47:case 48:case 95:case 52:case 51:case 46:case 79:return 200809;case 27:case 246:case 127:case 128:case 23:case 24:case 160:case 161:case 181:case 182:case 242:case 183:case 184:case 243:case 244:case 245:case 165:case 178:case 179:case 49:case 50:case 168:case 169:case 175:case 170:case 171:case 172:case 97:case 76:case 32:case 173:case 35:return-1;
case 176:case 177:case 7:case 155:case 8:case 157:case 125:case 126:case 92:case 93:case 129:case 130:case 131:case 94:case 91:return 1;case 74:case 60:case 69:case 70:case 4:return 1024;case 31:case 42:case 72:return 32;case 87:case 26:case 33:return 2147483647;case 34:case 1:return 47839;case 38:case 36:return 99;case 43:case 37:return 2048;case 0:return 2097152;case 3:return 65536;case 28:return 32768;case 44:return 32767;case 75:return 16384;case 39:return 1E3;case 89:return 700;case 71:return 256;
case 40:return 255;case 2:return 100;case 180:return 64;case 25:return 20;case 5:return 16;case 6:return 6;case 73:return 4;case 84:return"object"===typeof navigator?navigator.hardwareConcurrency||1:1}E[tc()>>2]=28;return-1}};
(function(){function b(g){a.asm=g.exports;J=a.asm.__indirect_function_table;z(J,"table not found in wasm exports");K--;a.monitorRunDependencies&&a.monitorRunDependencies(K);z(Oa["wasm-instantiate"]);delete Oa["wasm-instantiate"];0==K&&(null!==L&&(clearInterval(L),L=null),Na&&(g=Na,Na=null,g()))}function c(g){z(a===h,"the Module object should not be replaced during async compilation - perhaps the order of HTML elements is wrong?");h=null;b(g.instance)}function d(g){return Wa().then(function(m){return WebAssembly.instantiate(m,
f)}).then(g,function(m){w("failed to asynchronously prepare wasm: "+m);e(m)})}var f={env:uc,wasi_snapshot_preview1:uc};Pa();var h=a;if(a.instantiateWasm)try{return a.instantiateWasm(f,b)}catch(g){return w("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return ia||"function"!==typeof WebAssembly.instantiateStreaming||Sa()||"function"!==typeof fetch?d(c):fetch(Ta,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,f).then(c,function(m){w("wasm streaming compile failed: "+
m);w("falling back to ArrayBuffer instantiation");return d(c)})})})().catch(ba);return{}})();var rc=a.___wasm_call_ctors=M("__wasm_call_ctors"),sc=a._malloc=M("malloc"),Kb=a.___getTypeName=M("__getTypeName");a.___embind_register_native_and_builtin_types=M("__embind_register_native_and_builtin_types");var tc=a.___errno_location=M("__errno_location");a.stackSave=M("stackSave");a.stackRestore=M("stackRestore");a.stackAlloc=M("stackAlloc");a._setThrew=M("setThrew");var X=a._free=M("free");a._sbrk=M("sbrk");
a._emscripten_main_thread_process_queued_calls=M("emscripten_main_thread_process_queued_calls");a.dynCall_viijii=M("dynCall_viijii");a.dynCall_jiji=M("dynCall_jiji");a.dynCall_iiiiiijj=M("dynCall_iiiiiijj");a.dynCall_iiiiij=M("dynCall_iiiiij");a.dynCall_iiiiijj=M("dynCall_iiiiijj");Object.getOwnPropertyDescriptor(a,"intArrayFromString")||(a.intArrayFromString=function(){e("'intArrayFromString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"intArrayToString")||(a.intArrayToString=function(){e("'intArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ccall")||(a.ccall=function(){e("'ccall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"cwrap")||(a.cwrap=function(){e("'cwrap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setValue")||(a.setValue=function(){e("'setValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getValue")||(a.getValue=function(){e("'getValue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocate")||(a.allocate=function(){e("'allocate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"UTF8ArrayToString")||(a.UTF8ArrayToString=function(){e("'UTF8ArrayToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF8ToString")||(a.UTF8ToString=function(){e("'UTF8ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF8Array")||(a.stringToUTF8Array=function(){e("'stringToUTF8Array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToUTF8")||(a.stringToUTF8=function(){e("'stringToUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"lengthBytesUTF8")||(a.lengthBytesUTF8=function(){e("'lengthBytesUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){e("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnPreRun")||(a.addOnPreRun=function(){e("'addOnPreRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnInit")||(a.addOnInit=function(){e("'addOnInit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPreMain")||(a.addOnPreMain=function(){e("'addOnPreMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"addOnExit")||(a.addOnExit=function(){e("'addOnExit' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addOnPostRun")||(a.addOnPostRun=function(){e("'addOnPostRun' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeStringToMemory")||(a.writeStringToMemory=function(){e("'writeStringToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeArrayToMemory")||(a.writeArrayToMemory=function(){e("'writeArrayToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeAsciiToMemory")||(a.writeAsciiToMemory=function(){e("'writeAsciiToMemory' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addRunDependency")||(a.addRunDependency=function(){e("'addRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"removeRunDependency")||(a.removeRunDependency=function(){e("'removeRunDependency' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createFolder")||(a.FS_createFolder=function(){e("'FS_createFolder' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"FS_createPath")||(a.FS_createPath=function(){e("'FS_createPath' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createDataFile")||(a.FS_createDataFile=function(){e("'FS_createDataFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createPreloadedFile")||(a.FS_createPreloadedFile=function(){e("'FS_createPreloadedFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"FS_createLazyFile")||(a.FS_createLazyFile=function(){e("'FS_createLazyFile' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_createLink")||(a.FS_createLink=function(){e("'FS_createLink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"FS_createDevice")||(a.FS_createDevice=function(){e("'FS_createDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});
Object.getOwnPropertyDescriptor(a,"FS_unlink")||(a.FS_unlink=function(){e("'FS_unlink' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ). Alternatively, forcing filesystem support (-s FORCE_FILESYSTEM=1) can export this for you")});Object.getOwnPropertyDescriptor(a,"getLEB")||(a.getLEB=function(){e("'getLEB' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFunctionTables")||(a.getFunctionTables=function(){e("'getFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"alignFunctionTables")||(a.alignFunctionTables=function(){e("'alignFunctionTables' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerFunctions")||(a.registerFunctions=function(){e("'registerFunctions' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"addFunction")||(a.addFunction=function(){e("'addFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"removeFunction")||(a.removeFunction=function(){e("'removeFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){e("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"prettyPrint")||(a.prettyPrint=function(){e("'prettyPrint' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeBigInt")||(a.makeBigInt=function(){e("'makeBigInt' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){e("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getCompilerSetting")||(a.getCompilerSetting=function(){e("'getCompilerSetting' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"print")||(a.print=function(){e("'print' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"printErr")||(a.printErr=function(){e("'printErr' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTempRet0")||(a.getTempRet0=function(){e("'getTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setTempRet0")||(a.setTempRet0=function(){e("'setTempRet0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callMain")||(a.callMain=function(){e("'callMain' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"abort")||(a.abort=function(){e("'abort' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToNewUTF8")||(a.stringToNewUTF8=function(){e("'stringToNewUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscripten_realloc_buffer")||(a.emscripten_realloc_buffer=function(){e("'emscripten_realloc_buffer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ENV")||(a.ENV=function(){e("'ENV' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ERRNO_CODES")||(a.ERRNO_CODES=function(){e("'ERRNO_CODES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ERRNO_MESSAGES")||(a.ERRNO_MESSAGES=function(){e("'ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setErrNo")||(a.setErrNo=function(){e("'setErrNo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"DNS")||(a.DNS=function(){e("'DNS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getHostByName")||(a.getHostByName=function(){e("'getHostByName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GAI_ERRNO_MESSAGES")||(a.GAI_ERRNO_MESSAGES=function(){e("'GAI_ERRNO_MESSAGES' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Protocols")||(a.Protocols=function(){e("'Protocols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"Sockets")||(a.Sockets=function(){e("'Sockets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getRandomDevice")||(a.getRandomDevice=function(){e("'getRandomDevice' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"traverseStack")||(a.traverseStack=function(){e("'traverseStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UNWIND_CACHE")||(a.UNWIND_CACHE=function(){e("'UNWIND_CACHE' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"withBuiltinMalloc")||(a.withBuiltinMalloc=function(){e("'withBuiltinMalloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readAsmConstArgsArray")||(a.readAsmConstArgsArray=function(){e("'readAsmConstArgsArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readAsmConstArgs")||(a.readAsmConstArgs=function(){e("'readAsmConstArgs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"mainThreadEM_ASM")||(a.mainThreadEM_ASM=function(){e("'mainThreadEM_ASM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"jstoi_q")||(a.jstoi_q=function(){e("'jstoi_q' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jstoi_s")||(a.jstoi_s=function(){e("'jstoi_s' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getExecutableName")||(a.getExecutableName=function(){e("'getExecutableName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"listenOnce")||(a.listenOnce=function(){e("'listenOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"autoResumeAudioContext")||(a.autoResumeAudioContext=function(){e("'autoResumeAudioContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCallLegacy")||(a.dynCallLegacy=function(){e("'dynCallLegacy' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getDynCaller")||(a.getDynCaller=function(){e("'getDynCaller' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"dynCall")||(a.dynCall=function(){e("'dynCall' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"callRuntimeCallbacks")||(a.callRuntimeCallbacks=function(){e("'callRuntimeCallbacks' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"abortStackOverflow")||(a.abortStackOverflow=function(){e("'abortStackOverflow' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"reallyNegative")||(a.reallyNegative=function(){e("'reallyNegative' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unSign")||(a.unSign=function(){e("'unSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"reSign")||(a.reSign=function(){e("'reSign' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"formatString")||(a.formatString=function(){e("'formatString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"PATH")||(a.PATH=function(){e("'PATH' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PATH_FS")||(a.PATH_FS=function(){e("'PATH_FS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SYSCALLS")||(a.SYSCALLS=function(){e("'SYSCALLS' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"syscallMmap2")||(a.syscallMmap2=function(){e("'syscallMmap2' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"syscallMunmap")||(a.syscallMunmap=function(){e("'syscallMunmap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flush_NO_FILESYSTEM")||(a.flush_NO_FILESYSTEM=function(){e("'flush_NO_FILESYSTEM' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"JSEvents")||(a.JSEvents=function(){e("'JSEvents' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"specialHTMLTargets")||(a.specialHTMLTargets=function(){e("'specialHTMLTargets' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"maybeCStringToJsString")||(a.maybeCStringToJsString=function(){e("'maybeCStringToJsString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"findEventTarget")||(a.findEventTarget=function(){e("'findEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"findCanvasEventTarget")||(a.findCanvasEventTarget=function(){e("'findCanvasEventTarget' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"polyfillSetImmediate")||(a.polyfillSetImmediate=function(){e("'polyfillSetImmediate' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"demangle")||(a.demangle=function(){e("'demangle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"demangleAll")||(a.demangleAll=function(){e("'demangleAll' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"jsStackTrace")||(a.jsStackTrace=function(){e("'jsStackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackTrace")||(a.stackTrace=function(){e("'stackTrace' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getEnvStrings")||(a.getEnvStrings=function(){e("'getEnvStrings' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"checkWasiClock")||(a.checkWasiClock=function(){e("'checkWasiClock' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64")||(a.writeI53ToI64=function(){e("'writeI53ToI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToI64Clamped")||(a.writeI53ToI64Clamped=function(){e("'writeI53ToI64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToI64Signaling")||(a.writeI53ToI64Signaling=function(){e("'writeI53ToI64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeI53ToU64Clamped")||(a.writeI53ToU64Clamped=function(){e("'writeI53ToU64Clamped' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"writeI53ToU64Signaling")||(a.writeI53ToU64Signaling=function(){e("'writeI53ToU64Signaling' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromI64")||(a.readI53FromI64=function(){e("'readI53FromI64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"readI53FromU64")||(a.readI53FromU64=function(){e("'readI53FromU64' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"convertI32PairToI53")||(a.convertI32PairToI53=function(){e("'convertI32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"convertU32PairToI53")||(a.convertU32PairToI53=function(){e("'convertU32PairToI53' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exceptionLast")||(a.exceptionLast=function(){e("'exceptionLast' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exceptionCaught")||(a.exceptionCaught=function(){e("'exceptionCaught' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfoAttrs")||(a.ExceptionInfoAttrs=function(){e("'ExceptionInfoAttrs' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ExceptionInfo")||(a.ExceptionInfo=function(){e("'ExceptionInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"CatchInfo")||(a.CatchInfo=function(){e("'CatchInfo' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_addRef")||(a.exception_addRef=function(){e("'exception_addRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"exception_decRef")||(a.exception_decRef=function(){e("'exception_decRef' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"Browser")||(a.Browser=function(){e("'Browser' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"funcWrappers")||(a.funcWrappers=function(){e("'funcWrappers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getFuncWrapper")||(a.getFuncWrapper=function(){e("'getFuncWrapper' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"setMainLoop")||(a.setMainLoop=function(){e("'setMainLoop' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tempFixedLengthArray")||(a.tempFixedLengthArray=function(){e("'tempFixedLengthArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"miniTempWebGLFloatBuffers")||(a.miniTempWebGLFloatBuffers=function(){e("'miniTempWebGLFloatBuffers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"heapObjectForWebGLType")||(a.heapObjectForWebGLType=function(){e("'heapObjectForWebGLType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heapAccessShiftForWebGLHeap")||(a.heapAccessShiftForWebGLHeap=function(){e("'heapAccessShiftForWebGLHeap' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GL")||(a.GL=function(){e("'GL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGet")||(a.emscriptenWebGLGet=function(){e("'emscriptenWebGLGet' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"computeUnpackAlignedImageSize")||(a.computeUnpackAlignedImageSize=function(){e("'computeUnpackAlignedImageSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetTexPixelData")||(a.emscriptenWebGLGetTexPixelData=function(){e("'emscriptenWebGLGetTexPixelData' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetUniform")||(a.emscriptenWebGLGetUniform=function(){e("'emscriptenWebGLGetUniform' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emscriptenWebGLGetVertexAttrib")||(a.emscriptenWebGLGetVertexAttrib=function(){e("'emscriptenWebGLGetVertexAttrib' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"writeGLArray")||(a.writeGLArray=function(){e("'writeGLArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AL")||(a.AL=function(){e("'AL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL_unicode")||(a.SDL_unicode=function(){e("'SDL_unicode' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_ttfContext")||(a.SDL_ttfContext=function(){e("'SDL_ttfContext' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_audio")||(a.SDL_audio=function(){e("'SDL_audio' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"SDL")||(a.SDL=function(){e("'SDL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"SDL_gfx")||(a.SDL_gfx=function(){e("'SDL_gfx' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLUT")||(a.GLUT=function(){e("'GLUT' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"EGL")||(a.EGL=function(){e("'EGL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW_Window")||(a.GLFW_Window=function(){e("'GLFW_Window' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"GLFW")||(a.GLFW=function(){e("'GLFW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"GLEW")||(a.GLEW=function(){e("'GLEW' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"IDBStore")||(a.IDBStore=function(){e("'IDBStore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runAndAbortIfError")||(a.runAndAbortIfError=function(){e("'runAndAbortIfError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"emval_handle_array")||(a.emval_handle_array=function(){e("'emval_handle_array' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_free_list")||(a.emval_free_list=function(){e("'emval_free_list' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_symbols")||(a.emval_symbols=function(){e("'emval_symbols' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_emval")||(a.init_emval=function(){e("'init_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"count_emval_handles")||(a.count_emval_handles=function(){e("'count_emval_handles' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"get_first_emval")||(a.get_first_emval=function(){e("'get_first_emval' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getStringOrSymbol")||(a.getStringOrSymbol=function(){e("'getStringOrSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"requireHandle")||(a.requireHandle=function(){e("'requireHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_newers")||(a.emval_newers=function(){e("'emval_newers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftEmvalAllocator")||(a.craftEmvalAllocator=function(){e("'craftEmvalAllocator' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_get_global")||(a.emval_get_global=function(){e("'emval_get_global' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"emval_methodCallers")||(a.emval_methodCallers=function(){e("'emval_methodCallers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"InternalError")||(a.InternalError=function(){e("'InternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"BindingError")||(a.BindingError=function(){e("'BindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UnboundTypeError")||(a.UnboundTypeError=function(){e("'UnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"PureVirtualError")||(a.PureVirtualError=function(){e("'PureVirtualError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_embind")||(a.init_embind=function(){e("'init_embind' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInternalError")||(a.throwInternalError=function(){e("'throwInternalError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"throwBindingError")||(a.throwBindingError=function(){e("'throwBindingError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwUnboundTypeError")||(a.throwUnboundTypeError=function(){e("'throwUnboundTypeError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ensureOverloadTable")||(a.ensureOverloadTable=function(){e("'ensureOverloadTable' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"exposePublicSymbol")||(a.exposePublicSymbol=function(){e("'exposePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"replacePublicSymbol")||(a.replacePublicSymbol=function(){e("'replacePublicSymbol' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"extendError")||(a.extendError=function(){e("'extendError' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"createNamedFunction")||(a.createNamedFunction=function(){e("'createNamedFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredInstances")||(a.registeredInstances=function(){e("'registeredInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getBasestPointer")||(a.getBasestPointer=function(){e("'getBasestPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"registerInheritedInstance")||(a.registerInheritedInstance=function(){e("'registerInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"unregisterInheritedInstance")||(a.unregisterInheritedInstance=function(){e("'unregisterInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getInheritedInstance")||(a.getInheritedInstance=function(){e("'getInheritedInstance' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getInheritedInstanceCount")||(a.getInheritedInstanceCount=function(){e("'getInheritedInstanceCount' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"getLiveInheritedInstances")||(a.getLiveInheritedInstances=function(){e("'getLiveInheritedInstances' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredTypes")||(a.registeredTypes=function(){e("'registeredTypes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"awaitingDependencies")||(a.awaitingDependencies=function(){e("'awaitingDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"typeDependencies")||(a.typeDependencies=function(){e("'typeDependencies' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registeredPointers")||(a.registeredPointers=function(){e("'registeredPointers' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"registerType")||(a.registerType=function(){e("'registerType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"whenDependentTypesAreResolved")||(a.whenDependentTypesAreResolved=function(){e("'whenDependentTypesAreResolved' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_charCodes")||(a.embind_charCodes=function(){e("'embind_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind_init_charCodes")||(a.embind_init_charCodes=function(){e("'embind_init_charCodes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"readLatin1String")||(a.readLatin1String=function(){e("'readLatin1String' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getTypeName")||(a.getTypeName=function(){e("'getTypeName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"heap32VectorToArray")||(a.heap32VectorToArray=function(){e("'heap32VectorToArray' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"requireRegisteredType")||(a.requireRegisteredType=function(){e("'requireRegisteredType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"getShiftFromSize")||(a.getShiftFromSize=function(){e("'getShiftFromSize' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"integerReadValueFromPointer")||(a.integerReadValueFromPointer=function(){e("'integerReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"enumReadValueFromPointer")||(a.enumReadValueFromPointer=function(){e("'enumReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"floatReadValueFromPointer")||(a.floatReadValueFromPointer=function(){e("'floatReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"simpleReadValueFromPointer")||(a.simpleReadValueFromPointer=function(){e("'simpleReadValueFromPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructors")||(a.runDestructors=function(){e("'runDestructors' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"new_")||(a.new_=function(){e("'new_' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"craftInvokerFunction")||(a.craftInvokerFunction=function(){e("'craftInvokerFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"embind__requireFunction")||(a.embind__requireFunction=function(){e("'embind__requireFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"tupleRegistrations")||(a.tupleRegistrations=function(){e("'tupleRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"structRegistrations")||(a.structRegistrations=function(){e("'structRegistrations' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"genericPointerToWireType")||(a.genericPointerToWireType=function(){e("'genericPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"constNoSmartPtrRawPointerToWireType")||(a.constNoSmartPtrRawPointerToWireType=function(){e("'constNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"nonConstNoSmartPtrRawPointerToWireType")||(a.nonConstNoSmartPtrRawPointerToWireType=function(){e("'nonConstNoSmartPtrRawPointerToWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"init_RegisteredPointer")||(a.init_RegisteredPointer=function(){e("'init_RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer")||(a.RegisteredPointer=function(){e("'RegisteredPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_getPointee")||(a.RegisteredPointer_getPointee=function(){e("'RegisteredPointer_getPointee' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_destructor")||(a.RegisteredPointer_destructor=function(){e("'RegisteredPointer_destructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredPointer_deleteObject")||(a.RegisteredPointer_deleteObject=function(){e("'RegisteredPointer_deleteObject' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"RegisteredPointer_fromWireType")||(a.RegisteredPointer_fromWireType=function(){e("'RegisteredPointer_fromWireType' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"runDestructor")||(a.runDestructor=function(){e("'runDestructor' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"releaseClassHandle")||(a.releaseClassHandle=function(){e("'releaseClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"finalizationGroup")||(a.finalizationGroup=function(){e("'finalizationGroup' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer_deps")||(a.detachFinalizer_deps=function(){e("'detachFinalizer_deps' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"detachFinalizer")||(a.detachFinalizer=function(){e("'detachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"attachFinalizer")||(a.attachFinalizer=function(){e("'attachFinalizer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"makeClassHandle")||(a.makeClassHandle=function(){e("'makeClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"init_ClassHandle")||(a.init_ClassHandle=function(){e("'init_ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle")||(a.ClassHandle=function(){e("'ClassHandle' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_isAliasOf")||(a.ClassHandle_isAliasOf=function(){e("'ClassHandle_isAliasOf' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"throwInstanceAlreadyDeleted")||(a.throwInstanceAlreadyDeleted=function(){e("'throwInstanceAlreadyDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_clone")||(a.ClassHandle_clone=function(){e("'ClassHandle_clone' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_delete")||(a.ClassHandle_delete=function(){e("'ClassHandle_delete' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"deletionQueue")||(a.deletionQueue=function(){e("'deletionQueue' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"ClassHandle_isDeleted")||(a.ClassHandle_isDeleted=function(){e("'ClassHandle_isDeleted' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"ClassHandle_deleteLater")||(a.ClassHandle_deleteLater=function(){e("'ClassHandle_deleteLater' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"flushPendingDeletes")||(a.flushPendingDeletes=function(){e("'flushPendingDeletes' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"delayFunction")||(a.delayFunction=function(){e("'delayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"setDelayFunction")||(a.setDelayFunction=function(){e("'setDelayFunction' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"RegisteredClass")||(a.RegisteredClass=function(){e("'RegisteredClass' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"shallowCopyInternalPointer")||(a.shallowCopyInternalPointer=function(){e("'shallowCopyInternalPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"downcastPointer")||(a.downcastPointer=function(){e("'downcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"upcastPointer")||(a.upcastPointer=function(){e("'upcastPointer' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"validateThis")||(a.validateThis=function(){e("'validateThis' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_0")||(a.char_0=function(){e("'char_0' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"char_9")||(a.char_9=function(){e("'char_9' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"makeLegalFunctionName")||(a.makeLegalFunctionName=function(){e("'makeLegalFunctionName' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"warnOnce")||(a.warnOnce=function(){e("'warnOnce' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackSave")||(a.stackSave=function(){e("'stackSave' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stackRestore")||(a.stackRestore=function(){e("'stackRestore' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stackAlloc")||(a.stackAlloc=function(){e("'stackAlloc' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"AsciiToString")||(a.AsciiToString=function(){e("'AsciiToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"stringToAscii")||(a.stringToAscii=function(){e("'stringToAscii' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF16ToString")||(a.UTF16ToString=function(){e("'UTF16ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF16")||(a.stringToUTF16=function(){e("'stringToUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF16")||(a.lengthBytesUTF16=function(){e("'lengthBytesUTF16' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"UTF32ToString")||(a.UTF32ToString=function(){e("'UTF32ToString' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"stringToUTF32")||(a.stringToUTF32=function(){e("'stringToUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
Object.getOwnPropertyDescriptor(a,"lengthBytesUTF32")||(a.lengthBytesUTF32=function(){e("'lengthBytesUTF32' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8")||(a.allocateUTF8=function(){e("'allocateUTF8' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});Object.getOwnPropertyDescriptor(a,"allocateUTF8OnStack")||(a.allocateUTF8OnStack=function(){e("'allocateUTF8OnStack' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")});
a.writeStackCookie=Da;a.checkStackCookie=Ea;Object.getOwnPropertyDescriptor(a,"ALLOC_NORMAL")||Object.defineProperty(a,"ALLOC_NORMAL",{configurable:!0,get:function(){e("'ALLOC_NORMAL' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});Object.getOwnPropertyDescriptor(a,"ALLOC_STACK")||Object.defineProperty(a,"ALLOC_STACK",{configurable:!0,get:function(){e("'ALLOC_STACK' was not exported. add it to EXTRA_EXPORTED_RUNTIME_METHODS (see the FAQ)")}});var vc;
Na=function wc(){vc||xc();vc||(Na=wc)};
function xc(){function b(){if(!vc&&(vc=!0,a.calledRun=!0,!ja)){Ea();z(!La);La=!0;Xa(Ia);Ea();Xa(Ja);aa(a);if(a.onRuntimeInitialized)a.onRuntimeInitialized();z(!a._main,'compiled without a main, but one is present. if you added it from JS, use Module["onRuntimeInitialized"]');Ea();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var c=a.postRun.shift();Ka.unshift(c)}Xa(Ka)}}if(!(0<K)){Da();if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)Ma();
Xa(Ha);0<K||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b(),Ea())}}a.run=xc;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;xc();


  return ShellWasm.ready
}
);
})();
export default ShellWasm;